# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VectorBatchSaver
                                 A QGIS plugin
 Saves all Layers in defined formats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-21
        copyright            : (C) 2026 by changsan9527
        email                : changsan9527@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VectorBatchSaver class from file vector_batch_saver.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vector_batch_saver import VectorBatchSaver
    return VectorBatchSaver(iface)
