# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VectorBatchSaver
                                 A QGIS plugin
 Saves all Layers in defined formats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-11-21
        git sha              : $Format:%H$
        copyright            : (C) 2026 by changsan9527
        email                : changsan9527@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import QtCore, QtWidgets
from qgis.PyQt.QtCore import QCoreApplication, QSettings, QTranslator, qVersion
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog

# get some qgis libs:
from qgis.core import (
    Qgis,
    QgsCoordinateTransform,
    QgsMapLayer,
    QgsProject,
    QgsVectorFileWriter,
)

# Import the code for the dialog
from .vector_batch_saver_dialog import VectorBatchSaverDialog
import os
import os.path


class VectorBatchSaver:
    """QGIS Plugin Implementation."""

    if hasattr(QtCore.Qt, "ItemDataRole"):
        LAYER_ID_ROLE = QtCore.Qt.ItemDataRole.UserRole
    else:
        LAYER_ID_ROLE = QtCore.Qt.UserRole
    INFO_LEVEL = getattr(Qgis.MessageLevel, "Info", Qgis.Info)
    WARNING_LEVEL = getattr(Qgis.MessageLevel, "Warning", Qgis.Warning)
    CRITICAL_LEVEL = getattr(Qgis.MessageLevel, "Critical", Qgis.Critical)

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "VectorBatchSaver_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > "4.3.3":
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = VectorBatchSaverDialog()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&VectorBatchSaver")
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar("VectorBatchSaver")
        self.toolbar.setObjectName("VectorBatchSaver")
        self.dlg.lineEdit.clear()
        self.dlg.listWidget.setStyleSheet("""
            QListWidget::item:selected {
                background-color: #2F80ED;
                color: white;
            }
            QListWidget::item:selected:!active {
                background-color: #2F80ED;
                color: white;
            }
        """)
        self.dlg.toolButton.clicked.connect(self.select_output_directory)
        self.dlg.changeCRS.stateChanged.connect(self.trigger_crs)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("VectorBatchSaver", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(self.plugin_dir, "icon.svg")
        self.add_action(
            icon_path,
            text=self.tr("Batch save vector layers"),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(self.tr("&VectorBatchSaver"), action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    def select_output_directory(self):
        output_dir = QFileDialog.getExistingDirectory()
        self.dlg.lineEdit.setText(output_dir)

    def trigger_crs(self):
        self.dlg.mQgsProjectionSelectionWidget.setEnabled(
            self.dlg.changeCRS.isChecked()
        )

    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        self.dlg.show()
        layers = [
            tree_layer.layer()
            for tree_layer in QgsProject.instance().layerTreeRoot().findLayers()
        ]
        vector_layers = [
            layer for layer in layers if layer.type() == QgsMapLayer.VectorLayer
        ]

        if not vector_layers:
            self.iface.messageBar().pushMessage(
                "No vector layers",
                "Open at least one vector layer before exporting.",
                level=self.WARNING_LEVEL,
                duration=5,
            )
            return

        self.dlg.mQgsProjectionSelectionWidget.setCrs(QgsProject.instance().crs())

        # Add layer_list array to listWidget
        self.dlg.listWidget.clear()
        for layer in vector_layers:
            item = QtWidgets.QListWidgetItem()
            item.setText(layer.name())
            item.setData(self.LAYER_ID_ROLE, layer.id())
            item.setSelected(True)
            self.dlg.listWidget.addItem(item)
        self.dlg.listWidget.selectAll()
        # Run the dialog event loop
        result = self.dlg.exec()
        # See if OK was pressed
        if result:
            output_dir = self.dlg.lineEdit.text()
            if not os.path.exists(output_dir):
                self.iface.messageBar().pushMessage(
                    "No such directory",
                    "Choose an existing directory to save the layers in.",
                    level=self.WARNING_LEVEL,
                    duration=5,
                )
            if os.path.exists(output_dir):
                self.save_layers()

    def save_layers(self):
        if not self.dlg.listWidget.selectedItems():
            self.iface.messageBar().pushMessage(
                "No layers selected",
                "Select at least one vector layer to export.",
                level=self.WARNING_LEVEL,
                duration=5,
            )
            return

        if not any(
            [
                self.dlg.checkBox_shp.isChecked(),
                self.dlg.checkBox_tab.isChecked(),
                self.dlg.checkBox_geojson.isChecked(),
                self.dlg.checkBox_pgdump.isChecked(),
                self.dlg.checkBox_gpkg.isChecked(),
                self.dlg.checkBox_csv.isChecked(),
            ]
        ):
            self.iface.messageBar().pushMessage(
                "No file types selected",
                "Select at least one output format.",
                level=self.WARNING_LEVEL,
                duration=5,
            )
            return

        if self.dlg.checkBox_shp.isChecked():
            self.save_layer_format("Esri Shapefile")
        if self.dlg.checkBox_tab.isChecked():
            self.save_layer_format("MapInfo File")
        if self.dlg.checkBox_geojson.isChecked():
            self.save_layer_format("GeoJSON")
        if self.dlg.checkBox_pgdump.isChecked():
            self.save_layer_format("PGDump")
        if self.dlg.checkBox_gpkg.isChecked():
            self.save_layer_format("GPKG")
        if self.dlg.checkBox_csv.isChecked():
            self.save_layer_format("CSV")

    def write_vector_layer(
        self, layer, output_path, driver_name, crs, layer_options=None
    ):
        options = QgsVectorFileWriter.SaveVectorOptions()
        options.driverName = driver_name
        options.fileEncoding = "utf-8"
        options.layerOptions = layer_options or []
        options.ct = QgsCoordinateTransform(
            layer.crs(),
            crs,
            QgsProject.instance().transformContext(),
        )

        writer = QgsVectorFileWriter.writeAsVectorFormatV3(
            layer,
            output_path,
            QgsProject.instance().transformContext(),
            options,
        )
        return writer[0]

    def save_layer_format(self, format):
        layers = {
            tree_layer.layer().id(): tree_layer.layer()
            for tree_layer in QgsProject.instance().layerTreeRoot().findLayers()
            if tree_layer.layer().type() == QgsMapLayer.VectorLayer
        }
        output_dir = os.path.join(self.dlg.lineEdit.text(), format)
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

        formats = {
            "CSV": (".csv", ["GEOMETRY=AS_WKT"]),
            "Esri Shapefile": (".shp", []),
            "MapInfo File": (".TAB", []),
            "GeoJSON": (".GeoJSON", []),
            "PGDump": (".sql", []),
            "GPKG": (".gpkg", []),
        }
        extension, layer_options = formats[format]

        for item in self.dlg.listWidget.selectedItems():
            layer = layers.get(item.data(self.LAYER_ID_ROLE))
            if layer is None:
                continue

            if self.dlg.changeCRS.isChecked():
                crs = self.dlg.mQgsProjectionSelectionWidget.crs()
            else:
                crs = layer.crs()

            writer_error = self.write_vector_layer(
                layer,
                os.path.join(output_dir, layer.name() + extension),
                format,
                crs,
                layer_options,
            )
            if writer_error == QgsVectorFileWriter.NoError:
                self.iface.messageBar().pushMessage(
                    "Layer Saved",
                    layer.name() + " saved to " + output_dir + " as " + format,
                    level=self.INFO_LEVEL,
                    duration=2,
                )
            else:
                self.iface.messageBar().pushMessage(
                    "Error saving layer:",
                    layer.name() + extension + " to " + output_dir,
                    level=self.CRITICAL_LEVEL,
                    duration=2,
                )
